# ========================================
# EXAMPLE DOCKER TOOL CONFIG
# ========================================
[anchore-syft]
SOURCE = "python:3.8-slim"
REPORT_FILE = "reports/container/syft-report-sbom.json"
INTERMEDIATE_FILE = "reports/container/syft-report-sbom.xml"

[container-trivy]
IMAGE_NAME = "python:3.8-slim"
REPORT_FILE = "reports/container/trivy-report.json"

[anchore-grype]
SOURCE = "python:3.8-slim"
REPORT_FILE = "reports/container/grype-report.json"

[semgrep]
# HIGHLY RECOMMENDED, Docker rule set extremely good
# https://semgrep.dev/p/dockerfile
# Path to DockerFile
SOURCE = "Dockerfile"
CONFIGS = [
    "p/dockerfile"
]
REPORT_FILE = "reports/container/semgrep-report.json"

[trufflehog]
SOURCE = ["."]
INCLUDE_FULL_REASON = true
REPORT_FILE = "reports/container/trufflehog-report.json"

[kics]
SOURCE = "Dockerfile"
REPORT_FILE = "reports/container/kics-report.json"

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://aio7y6esb7.execute-api.eu-west-2.amazonaws.com/development"
CODEBASE_ID = "goat-container-docker"
CODEBRANCH_NAME = "main"

[bom]
REPORT_FILE = "reports/container/report-cyclonedx-sbom.json"

[json]
REPORT_FILE = "reports/container/eze_report.json"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["container-trivy", "anchore-grype", "anchore-syft", "semgrep", "trufflehog", "gitleaks", "kics"]
reporters = ["console", "json", "bom"]

[scan.ci]
tools = ["container-trivy", "anchore-grype", "semgrep", "trufflehog"]
# BUG AB-626: tools = ["container-trivy", "anchore-grype", "anchore-syft", "semgrep", "trufflehog"]
reporters = ["console", "bom", "eze"]
