# ========================================
# EXAMPLE DOCKER TOOL CONFIG
# ========================================
[anchore-syft]
SOURCE = "python:3.8-slim"
INTERMEDIATE_FILE = ".eze/container/syft-report-sbom.xml"

[container-trivy]
IMAGE_NAME = "python:3.8-slim"

[anchore-grype]
SOURCE = "python:3.8-slim"

[semgrep]
# HIGHLY RECOMMENDED, Docker rule set extremely good
# https://semgrep.dev/p/dockerfile
# Path to DockerFile
SOURCE = "Dockerfile"
CONFIGS = [
    "p/dockerfile"
]

[trufflehog]
SOURCE = ["."]
INCLUDE_FULL_REASON = true

[kics]
# Full List of Fields and Tool Help available "docker run riversafe/eze-cli tools help kics"
WINDOWS_DOCKER_WORKAROUND = false
EXCLUDE = []

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://aio7y6esb7.execute-api.eu-west-2.amazonaws.com/development"
CODEBASE_ID = "goat-container-docker"
CODEBRANCH_NAME = "main"

[bom]

[json]

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["anchore-grype", "anchore-syft", "container-trivy", "kics", "semgrep", "trufflehog", "gitleaks"]
reporters = ["console", "json", "bom"]

[scan.ci]
tools = ["trufflehog","semgrep","kics"]
# BUG AB-626 / AB-1000: tools = ["container-trivy", "anchore-grype", "anchore-syft", "semgrep", "trufflehog"]
reporters = ["console", "bom", "eze","html"]
