# Eze Starter pipeline
# Minimal pipeline that runs eze tool
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

# https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
- script: |
    cd scripts
    chmod +x install-eze.sh
    chmod +x run-eze.sh
    ./install-eze.sh
  displayName: 'Run eze test'

- script: |
    cd goat-node
    eze test -s ci --debug
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Node Goat'

- script: |
    cd goat-python
    eze test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Python Goat'

- script: |
    cd goat-java
    eze test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Java Goat'

- script: |
    cd goat-secrets
    eze test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Secrets Goat'