# Eze Starter pipeline
# Minimal pipeline that runs eze tool
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

# https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
- script: |
    docker pull riversafe/eze-cli:latest
  displayName: 'Pull eze docker'

- script: |
    chmod  o+rw goat-container
    cd goat-container
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Container'

- script: |
    chmod  o+rw goat-node
    cd goat-node
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Node Goat'

- script: |
    chmod  o+rw goat-python
    cd goat-python
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Python Goat'

# The line of chmod... is to handle writing permissions running Docker in this pipeline.
- script: |
    chmod  o+rw goat-java
    cd goat-java
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Java Goat'

- script: |
    chmod  o+rw goat-node
    cd goat-secrets
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Secrets Goat'