# Eze Starter pipeline
# Minimal pipeline that runs eze tool
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

# https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
- script: |
    docker pull riversafe/eze-cli:latest
  displayName: 'Pull eze docker'

- script: |
    chmod o+rw goat-container
    cd goat-container
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Container'

- script: |
    cd goat-node
    chmod o+rw insecure
    cd insecure
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Node Goat: Insecure Package'

- script: |
    cd goat-node
    chmod o+rw damaged-package
    cd damaged-package
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Node Goat: Damaged Package'

- script: |
    chmod o+rw goat-python
    cd goat-python
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Python Goat'

- script: |
    cd goat-java
    chmod o+rw insecure
    cd insecure
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Java Goat: Insecure Pom'

- script: |
    cd goat-java
    chmod o+rw damaged-pom
    cd damaged-pom
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Java Goat: Damaged Pom'

- script: |
    chmod o+rw goat-secrets
    cd goat-secrets
    docker run --rm -e "EZE_APIKEY=$EZE_APIKEY" -e "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME" -e "BUILD_REPOSITORY_URI=$BUILD_REPOSITORY_URI" -v "$(pwd)":/data riversafe/eze-cli test -s ci
  env:
    EZE_APIKEY: $(EZE_APIKEY)
  displayName: 'Run Eze against Secrets Goat'