# ========================================
# TOOL CONFIG
# ========================================
[node-npmaudit]

[semgrep]
PRINT_TIMING_INFO = true
CONFIGS = [
    "p/ci",
    "p/nodejs",
    "p/javascript",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "src/"

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[eze]
CONSOLE_ENDPOINT = "https://lff3adj48f.execute-api.eu-west-2.amazonaws.com/staging"
CODEBASE_ID = "584127a9-1900-49c4-97ce-95e61ba18048"


# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "node-npmaudit", "node-npmoutdated", "node-cyclonedx"]
reporters = ["console"]


[scan.linux]
tools = ["trufflehog", "node-npmaudit", "node-npmoutdated", "semgrep", "node-cyclonedx"]
reporters = ["console"]

[scan.ci]
tools = ["trufflehog:ci", "node-npmaudit", "node-npmoutdated", "semgrep", "node-cyclonedx"]
reporters = ["console", "eze"]