# ========================================
# TOOL CONFIG
# ========================================
[node-npmaudit]

[semgrep]
PRINT_TIMING_INFO = true
CONFIGS = [
    "p/ci",
    "p/nodejs",
    "p/javascript",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "."
EXCLUDE = [
    "node_modules",
    "package-lock.json"
]

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://lff3adj48f.execute-api.eu-west-2.amazonaws.com/staging"
CODEBASE_ID = "goat-node"
CODEBRANCH_NAME = "main"


# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "node-npmaudit", "node-npmoutdated", "node-cyclonedx"]
reporters = ["console", "json"]


[scan.linux]
tools = ["trufflehog", "node-npmaudit", "node-npmoutdated", "semgrep", "node-cyclonedx"]
reporters = ["console", "json"]

[scan.ci]
tools = ["trufflehog:ci", "node-npmaudit", "node-npmoutdated", "semgrep", "node-cyclonedx"]
reporters = ["console", "eze"]