# ========================================
# TOOL CONFIG
# ========================================
[node-npmaudit]

[semgrep]
PRINT_TIMING_INFO = false
CONFIGS = [
    "p/ci",
    "p/nodejs",
    "p/javascript",
]
EXCLUDE = [
    "tests",
    "node_modules/"
]

[trufflehog]
SOURCE = "."
EXCLUDE = [
    "node_modules",
    "package-lock.json"
]

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "node-cyclonedx", "semgrep", "node-npmaudit"]
reporters = ["console", "json", "sarif"]

