# ========================================
# TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "src"

[semgrep]
PRINT_TIMING_INFO = false
CONFIGS = [
    "p/ci",
    "p/python",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "src/"

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://aio7y6esb7.execute-api.eu-west-2.amazonaws.com/development"
CODEBASE_ID = "goat-python"
CODEBRANCH_NAME = "main"

[s3]
OBJECT_KEY = "uploaded20211218.json"
AWS_ACCESS_KEY = "introduce_access_key_or_set_environmental_variable"
AWS_SECRET_KEY = "introduce_secret_key_or_set_environmental_variable"

[markdown]

[sarif]

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "python-bandit", "python-cyclonedx", "trufflehog-v3"]
reporters = ["console", "markdown", "sarif"]

[scan.ci]
tools = ["trufflehog:ci", "python-bandit", "semgrep"]
reporters = ["console", "eze"]
