# ========================================
# TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "src"

[python-piprot]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "low"

[python-safety]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "medium"

[semgrep]
PRINT_TIMING_INFO = false
CONFIGS = [
    "p/ci",
    "p/python",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "src/"

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://7i41x6vk0a.execute-api.eu-west-2.amazonaws.com/development"
CODEBASE_ID = "goat-python"
CODEBRANCH_NAME = "main"

[s3]
OBJECT_KEY = "uploaded20211218.json"
AWS_ACCESS_KEY = "introduce_access_key_or_set_environmental_variable"
AWS_SECRET_KEY = "introduce_secret_key_or_set_environmental_variable"

[markdown]
REPORT_FILE = "reports/eze-md.md"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "python-piprot", "python-bandit", "python-safety", "python-cyclonedx"]
reporters = ["markdown"]

[scan.ci]
tools = ["trufflehog:ci", "python-piprot", "python-bandit", "python-safety", "semgrep"]
reporters = ["console", "eze"]