# ========================================
# TOOL CONFIG
# ========================================
[node-npmaudit]

[semgrep]
PRINT_TIMING_INFO = false
CONFIGS = [
    "p/ci",
    "p/nodejs",
    "p/javascript",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "."
EXCLUDE = [
    "node_modules",
    "package-lock.json"
]

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://aio7y6esb7.execute-api.eu-west-2.amazonaws.com/development"
CODEBASE_ID = "goat-node"
CODEBRANCH_NAME = "main"

[sarif]
REPORT_FILE = "reports/container/eze_report.sarif"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "node-npmaudit", "node-npmoutdated", "semgrep", "node-cyclonedx"]
reporters = ["console", "json", "sarif"]


[scan.ci]
tools = ["trufflehog:ci", "node-npmaudit", "node-npmoutdated", "semgrep", "node-cyclonedx"]
reporters = ["console", "eze"]