# ========================================
# TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "src"

[python-piprot]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "low"

[python-safety]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "medium"

[semgrep]
PRINT_TIMING_INFO = false
CONFIGS = [
    "p/ci",
    "p/python",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "src/"

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

[eze]
CONSOLE_ENDPOINT = "https://aio7y6esb7.execute-api.eu-west-2.amazonaws.com/development"
CODEBASE_ID = "goat-python-unpinned"
CODEBRANCH_NAME = "main"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["python-cyclonedx"]
#tools = ["trufflehog", "semgrep", "python-bandit", "python-safety", "python-piprot", "python-cyclonedx"]
reporters = ["console", "json"]

[scan.ci]
tools = ["trufflehog:ci", "semgrep", "python-bandit", "python-safety", "python-piprot", "python-cyclonedx"]
reporters = ["console", "eze"]